theme: jekyll-theme-cayman

title: Frekele
description: Leandro Kersting de Freitas
google_analytics: true
show_downloads: true

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
